version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\anisimovsergey\go-gems

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.9

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go build -o buildOutput\go-gems -i .
